Feature/sc 26301/add tests vpc module
Cyber4All/terraform-cyber4all-catalog pull request #39
Opened 2023-10-16 14:58 UTC by JosueMolinaMorales

Adds tests for the vpc module

2023-10-17 13:08 UTC, Cwagne17 commented on modules/vpc/main.tf
> +  num_availability_zones = var.num_availability_zones == null ? length(data.aws_availability_zones.current.names) : var.num_availability_zones
If we have to reference `.names` here. Does this also need to be referenced later in the config where the actual availability zone name is being used?

2023-10-17 13:21 UTC, Cwagne17 requested changes
Just a few questions & requests. The testing is looking really good. Could we also add doc comments to functions? https://tip.golang.org/doc/comment

2023-10-17 13:21 UTC, Cwagne17 commented on test/modules/vpc.go
> +			"region": awsRegion,
Do we need to namespace the name of the VPC to avoid conflict?

2023-10-17 13:21 UTC, Cwagne17 commented on test/modules/vpc.go
> +				Values: []*string{aws_sdk.String("Private Subnet")},
The Name tag for a private subnet is formatted like `"${var.vpc_name}-private-%s"` likewise, the public subnet is formatted like `"${var.vpc_name}-public-%s"` where the `%s` is the availability zone name.

2023-10-17 13:21 UTC, Cwagne17 commented on test/modules/vpc.go
> +	acls, err := ec2Client.DescribeNetworkAcls(&ec2.DescribeNetworkAclsInput{})
Currently our NACL are allowing allow ingress/egress.

2023-10-17 13:21 UTC, Cwagne17 commented on test/modules/vpc.go
> +	acls, err := ec2Client.DescribeNetworkAcls(&ec2.DescribeNetworkAclsInput{})
So its ok if we don't check this, as long as they exist for now.

2023-10-17 13:21 UTC, Cwagne17 commented on test/modules/vpc.go
> +	assert.NotEqual(t, 0, len(igtw.InternetGateways), "Expected at least 1 Internet Gateway, got 0")
Can we add newlines between the assertions for readability?

2023-10-17 13:21 UTC, Cwagne17 commented on test/modules/vpc.go
> +func assertCidrBlocksAreCorrect(t *testing.T, terraformOptions *terraform.Options, numAzs int) {
Should this be renamed to `assertPrivateCidrBlocksAreCorrect`?

2023-10-20 12:38 UTC, JosueMolinaMorales commented
> Looks good, but tests are failing.

You're failing

2023-10-25 20:05 UTC, merged